# Generated by Django 4.0.4 on 2022-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
