# Generated by Django 4.0.4 on 2022-04-28 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0002_contact_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=101)),
                ('slug', models.CharField(default=models.CharField(max_length=101), max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.FloatField()),
                ('details', models.TextField()),
                ('available', models.BooleanField()),
                ('category', models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
