# Generated by Django 4.0.4 on 2022-04-29 06:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='medium',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Bangla', 'Bangla'), ('Math', 'Math'), ('Science', 'Science')], default='Bangla', max_length=100),
        ),
    ]
