# Generated by Django 4.0.4 on 2022-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0008_alter_post_class_in_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='class_in',
            field=models.ManyToManyField(related_name='class_in_set', to='tuition.class_in'),
        ),
    ]
